# ============================================================================
# Synapse loader - per-user build credentials.
#
# Writes FUL\src\Loader\Auth\creds.h with the baked login for ONE
# account. The access key is NEVER written as plaintext: only its salted
# SHA-256 (uppercase hex) lands in the binary.
#
# Usage:
#   .\make-creds.ps1 -Username fixeon -AccessKey "correct-horse" -Expires "2026-12-31" -BuildId "fixeon-a4k9"
#
# Omitting -BuildId generates a unique one. -Expires defaults to "Never".
# Re-run before each user build; the release workflow should loop this script
# over the roster, compile + Themida-pack each output, and ship.
# ============================================================================
param(
    [Parameter(Mandatory = $true)][string]$Username,
    [Parameter(Mandatory = $true)][string]$AccessKey,
    [string]$Expires = "Never",
    [string]$BuildId = ""
)

$ErrorActionPreference = "Stop"

# Public salt — must match Auth.cpp's Salt() constant.
$Salt = "Synapse:k:7f3d9c2a:1b4e:4f8a:9c2d:e5f1a2b3c4d5"

if ([string]::IsNullOrWhiteSpace($Username)) { throw "Username is required." }
if ([string]::IsNullOrEmpty($AccessKey)) { throw "AccessKey is required." }
if ($AccessKey.Length -lt 8) { throw "AccessKey is too short (min 8 chars)." }
if (-not [string]::IsNullOrEmpty($Expires) -and $Expires -ne "Never" -and $Expires -notmatch '^\d{4}-\d{2}-\d{2}$') {
    throw "Expires must be 'Never' or YYYY-MM-DD."
}
if ([string]::IsNullOrWhiteSpace($BuildId)) {
    $BuildId = "$([guid]::NewGuid().ToString('N').Substring(0, 8))"
}

$sha = [System.Security.Cryptography.SHA256]::Create()
$hashBytes = $sha.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($AccessKey + $Salt))
$hashUpper = (($hashBytes | ForEach-Object { $_.ToString("x2") }) -join "").ToUpperInvariant()

$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$outPath = Join-Path $projectRoot "FUL\src\Loader\Auth\creds.h"

$content = @"
// Autogenerated by make-creds.ps1 - do not edit manually.
#pragma once

#define SYNAPSE_CRED_USERNAME "$Username"
#define SYNAPSE_CRED_KEY_HASH "$hashUpper"
#define SYNAPSE_CRED_EXPIRES "$Expires"
#define SYNAPSE_CRED_BUILD "$BuildId"
"@

Set-Content -LiteralPath $outPath -Value $content -Encoding ASCII

Write-Host "Wrote $outPath"
Write-Host "  Username : $Username"
Write-Host "  Key hash : $hashUpper  (plaintext key is NOT stored)"
Write-Host "  Expires  : $Expires"
Write-Host "  Build id : $BuildId"