#pragma once
#include <string>

// Per-user credential client for the Synapse builds.
//
// Each released loader is compiled with its own baked-in account (see
// creds.h, generated by the release workflow) so no two builds share a
// login; the binary only ever stores the salted SHA-256 of the access key
// plus the remote metadata endpoints:
//   config.json  -> { version, changelog, status, ... }    (hand edited)
//
// When creds.h is empty (local dev builds) Login() falls back to the remote
// auth.json lookup so dev testing still works against the panel.
namespace Auth
{
	struct Session
	{
		bool ok = false;
		std::string error;
		std::string user;
		std::string expires;   // "Never" or "YYYY-MM-DD"
		std::string buildId;   // unique per-build tag (baked builds only)
		std::string version;   // current private build (config.json)
		std::string changelog; // release notes (config.json)
		std::string status;    // "detected" | "undetected" | "" (config.json)
	};

	// Endpoints are compile-time xor-encrypted strings.
	const std::string& BaseUrl();      // https://yoursite.here
	const std::string& LoaderExeUrl(); // https://yoursite.here/loader.exe

	// Version string baked into the loader (product + PE build timestamp).
	const std::string& ClientVersion();

	// Unique per-build tag baked into this copy ("" for dev builds).
	const std::string& BuildId();

	// Verifies the entered credentials. Baked builds check against creds.h
	// locally (no network); dev builds verify against auth.json by re-hashing
	// the key client-side (salt baked in). If the panel is reachable, this
	// also pulls version/changelog/status from config.json.
	Session Login(const std::string& user, const std::string& key);

	// GET config.json - public metadata fetch (offline-safe).
	void FetchMeta(std::string& version, std::string& changelog, std::string& status);
}